[package]
name = "flight-comms-esp"
version = "0.1.0"
edition = "2024"

[dependencies]
flight-core = { path = "../flight-core" }
esp-radio = { version = "1.0.0-beta.0", features = ["esp32s3", "esp-now", "esp-alloc", "unstable"], default-features = false }
postcard = { version = "1.1", default-features = false }
esp-println = { version = "0.18.0", features = ["esp32s3"] }
embassy-executor = { version = "0.10.0" }
